CONNECT TO db2_server1 USER db2qrepId USING password;
 
INSERT INTO ASN.IBMQREP_SIGNAL (   SIGNAL_TIME,    SIGNAL_TYPE,    SIGNAL_SUBTYPE,    SIGNAL_INPUT_IN,    SIGNAL_STATE) VALUES
        (     CURRENT TIMESTAMP,    'CMD',    'CAPSTART',    'TABLENAME0001',    'P' );
 
COMMIT WORK;
CONNECT RESET;
TERMINATE;
