ASNCLP SESSION SET TO Q REPLICATION;

SET RUN SCRIPT NOW STOP ON SQL ERROR ON;

# Define bidirectional replication nodes
SET BIDI NODE 1 SERVER DBALIAS db_server1
ID db2qrepid PASSWORD "password" SCHEMA asn;
SET BIDI NODE 2 SERVER DBALIAS db_server2
ID db2qrepid PASSWORD "password" SCHEMA asn;

# create q replication map for replication from server1 to server2
CREATE REPLQMAP SERVER1_TO_SERVER2_MAP ( NODE 1, NODE 2 ) USING
ADMINQ "ADMINQ_SERVER1"
RECVQ "RECVQ_SERVER1_TO_SERVER2"
SENDQ "RECVQ_SERVER1_TO_SERVER2"
MEMORY LIMIT memoryMax
MAX MESSAGE SIZE messageMax;

# Cretae q replication map for replication from server2 to server1
CREATE REPLQMAP SERVER2_TO_SERVER1_MAP ( NODE 2, NODE 1 ) USING
ADMINQ "ADMINQ_SERVER2"
RECVQ "RECVQ_SERVER2_TO_SERVER1"
SENDQ "RECVQ_SERVER2_TO_SERVER1"
MEMORY LIMIT memoryMax
MAX MESSAGE SIZE messageMax;

QUIT;
