ASNCLP SESSION SET TO Q REPLICATION;

SET RUN SCRIPT NOW STOP ON SQL ERROR ON;
SET LOG "qcontrol.err";

# Define capture server and target server
SET SERVER CAPTURE TO DBALIAS DB_SERVER2 ID db2qrepid PASSWORD "password";
SET SERVER TARGET TO DBALIAS DB_SERVER2 ID db2qrepid PASSWORD "password";

# Define capture and apply schemas
SET CAPTURE SCHEMA SOURCE ASN;
SET APPLY SCHEMA ASN;

# Define Queues managers for schema at sever2
SET QMANAGER "QM_SERVER2" FOR CAPTURE SCHEMA;
SET QMANAGER "QM_SERVER2" FOR APPLY SCHEMA;

# Create control tables 
CREATE CONTROL TABLES FOR CAPTURE SERVER USING RESTARTQ "ASN.RESTARTQ_SERVER2" ADMINQ "ASN.ADMINQ_SERVER2";
CREATE CONTROL TABLES FOR APPLY SERVER;
