ASNCLP SESSION SET TO Q REPLICATION;
SET RUN SCRIPT NOW STOP ON SQL ERROR ON;

SET BIDI NODE 1 SERVER DBALIAS db_server1 ID db2qrepid PASSWORD "password" SCHEMA asn;
SET BIDI NODE 2 SERVER DBALIAS db_server2 ID db2qrepid PASSWORD "password" SCHEMA asn;

SET SUBGROUP "ASN_GROUP";

SET CONNECTION SOURCE db_server1.asn TARGET db_server2.asn REPLQMAP SERVER1_TO_SERVER2_MAP ;
SET CONNECTION SOURCE db_server2.asn TARGET db_server1.asn REPLQMAP SERVER2_TO_SERVER1_MAP ;
 
SET TABLES (db_server1.asn.db2qrepid.tableName, db_server2.asn.db2qrepId.tableName);

CREATE QSUB SUBTYPE B
FROM NODE db2_server1.asn 
     SOURCE ALL CHANGED ROWS Y HAS LOAD PHASE I REPLICATE ADD COLUMN Y START AUTOMATICALLY YES 
     TARGET CONFLICT RULE A CONFLICT ACTION F OKSQLSTATES "23505" 
FROM NODE db2_server2.asn 
     SOURCE ALL CHANGED ROWS Y HAS LOAD PHASE E REPLICATE ADD COLUMN Y 
     TARGET CONFLICT RULE A CONFLICT ACTION I OKSQLSTATES "23505" 
COLS ALL;
